services:
  jenkins:
    image: 127.0.0.1:5000/jenkins:latest
    user: root
    volumes:
      - jenkins_home:/var/lib/jenkins
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 50000
        published: 50000
        protocol: tcp
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
volumes:
  jenkins_home:
