lock-version = "1.0"
environments = ["sys_platform == 'linux'"]
requires-python = ">=3.12"
created-by = "tiny-swarm-world"

[[packages]]
name = "annotated-types"
version = "0.7.0"
index = "https://pypi.org/simple/"

[[packages]]
name = "certifi"
version = "2024.7.4"
index = "https://pypi.org/simple/"

[[packages]]
name = "charset-normalizer"
version = "3.4.1"
index = "https://pypi.org/simple/"

[[packages]]
name = "idna"
version = "3.10"
index = "https://pypi.org/simple/"

[[packages]]
name = "pydantic"
version = "2.10.6"
index = "https://pypi.org/simple/"
dependencies = [
  {name = "annotated-types"},
  {name = "pydantic-core"},
  {name = "typing-extensions"},
]

[[packages]]
name = "pydantic-core"
version = "2.27.2"
index = "https://pypi.org/simple/"
dependencies = [
  {name = "typing-extensions"},
]

[[packages]]
name = "PyYAML"
version = "6.0.1"
index = "https://pypi.org/simple/"

[[packages]]
name = "requests"
version = "2.32.0"
index = "https://pypi.org/simple/"
dependencies = [
  {name = "certifi"},
  {name = "charset-normalizer"},
  {name = "idna"},
  {name = "urllib3"},
]

[[packages]]
name = "ruamel.yaml"
version = "0.17.21"
index = "https://pypi.org/simple/"
dependencies = [
  {name = "ruamel.yaml.clib"},
]

[[packages]]
name = "ruamel.yaml.clib"
version = "0.2.8"
index = "https://pypi.org/simple/"

[[packages]]
name = "typing-extensions"
version = "4.15.0"
index = "https://pypi.org/simple/"

[[packages]]
name = "urllib3"
version = "2.0.7"
index = "https://pypi.org/simple/"
