[pytest]
testpaths = tests
pythonpath = src
norecursedirs =
    .git
    .mypy_cache
    .pytest_cache
    .ruff_cache
    .tiny-swarm
    .tiny-swarm-world
    .venv
    bin
    lib
    venv
addopts = -ra
