services:
  nexus:
    image: sonatype/nexus3:3.75.1
    volumes:
      - nexus-data:/nexus-data
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
      - target: 5000
        published: 5000
        protocol: tcp
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
volumes:
  nexus-data:
