import ast
import re
import tomllib
import unittest
from pathlib import Path

import yaml
from packaging.requirements import Requirement
from packaging.version import Version


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]


class TestPackageMetadata(unittest.TestCase):
    def _setup_keyword_values(self) -> dict[str, ast.expr]:
        setup_tree = ast.parse((REPOSITORY_ROOT / "setup.py").read_text(encoding="utf-8"))
        setup_call = next(
            node
            for node in ast.walk(setup_tree)
            if isinstance(node, ast.Call) and getattr(node.func, "id", None) == "setup"
        )
        keyword_values: dict[str, ast.expr] = {}
        for keyword in setup_call.keywords:
            assert keyword.arg is not None
            keyword_values[keyword.arg] = keyword.value
        return keyword_values

    def test_pyproject_declares_package_metadata_and_cli_entrypoint(self):
        pyproject = tomllib.loads((REPOSITORY_ROOT / "pyproject.toml").read_text(encoding="utf-8"))

        self.assertEqual(pyproject["project"]["name"], "tiny-swarm-world")
        self.assertEqual(pyproject["project"]["requires-python"], ">=3.12")
        self.assertEqual(
            pyproject["project"]["scripts"]["tiny-swarm-world"],
            "tiny_swarm_world.__main__:cli",
        )
        self.assertEqual(pyproject["tool"]["setuptools"]["packages"]["find"]["where"], ["src"])

    def test_pyproject_dependencies_match_runtime_requirements(self):
        requirements = [
            line.strip()
            for line in (REPOSITORY_ROOT / "requirements.txt").read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.strip().startswith("#")
        ]
        pyproject = tomllib.loads((REPOSITORY_ROOT / "pyproject.toml").read_text(encoding="utf-8"))

        self.assertEqual(requirements, pyproject["project"]["dependencies"])

    def test_environment_declares_ruff_quality_tool(self):
        environment = yaml.safe_load((REPOSITORY_ROOT / "environment.yml").read_text(encoding="utf-8"))
        conda_dependencies = [
            dependency for dependency in environment["dependencies"] if isinstance(dependency, str)
        ]

        self.assertIn("ruff", conda_dependencies)
        self.assertNotIn("flake8", conda_dependencies)

        pip_dependencies = next(
            dependency["pip"]
            for dependency in environment["dependencies"]
            if isinstance(dependency, dict) and "pip" in dependency
        )
        self.assertEqual(pip_dependencies, ["-r requirements.lock", "-r requirements-dev.txt"])

    def test_hashed_runtime_lock_satisfies_direct_requirements(self):
        lock_text = (REPOSITORY_ROOT / "requirements.lock").read_text(encoding="utf-8")
        locked_versions = {}
        for line in lock_text.splitlines():
            if "==" not in line or line.lstrip().startswith("#"):
                continue
            name, version_with_suffix = line.split("==", 1)
            locked_versions[re.sub(r"[-_.]+", "-", name.strip().lower())] = Version(
                version_with_suffix.split()[0].strip(" \\")
            )

        requirements = [
            Requirement(line.strip())
            for line in (REPOSITORY_ROOT / "requirements.txt").read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.strip().startswith("#")
        ]
        for requirement in requirements:
            normalized_name = re.sub(r"[-_.]+", "-", requirement.name.lower())
            with self.subTest(requirement=requirement.name):
                self.assertIn(normalized_name, locked_versions)
                self.assertIn(locked_versions[normalized_name], requirement.specifier)

        self.assertIn("--hash=sha256:", lock_text)
        self.assertFalse((REPOSITORY_ROOT / "pylock.toml").exists())

    def test_python_312_ci_clean_installs_locked_editable_project(self):
        lock_text = (REPOSITORY_ROOT / "requirements.lock").read_text(encoding="utf-8")
        workflow_text = (REPOSITORY_ROOT / ".github/workflows/sonar_check.yml").read_text(
            encoding="utf-8"
        )

        self.assertIn("autogenerated by pip-compile with Python 3.12", lock_text)
        self.assertIn('python-version: "3.12"', workflow_text)
        self.assertIn("pip install --require-hashes -r requirements.lock", workflow_text)
        self.assertIn("pip install --no-deps -e .", workflow_text)

    def test_package_versions_are_aligned(self):
        pyproject = tomllib.loads((REPOSITORY_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
        setup_version = ast.literal_eval(self._setup_keyword_values()["version"])

        self.assertEqual(pyproject["project"]["version"], setup_version)

    def test_setup_py_keeps_legacy_console_script_compatible(self):
        keyword_values = self._setup_keyword_values()

        self.assertIn("entry_points", keyword_values)
        entry_points = ast.literal_eval(keyword_values["entry_points"])
        self.assertEqual(
            entry_points["console_scripts"],
            ["tiny-swarm-world=tiny_swarm_world.__main__:cli"],
        )


if __name__ == "__main__":
    unittest.main()
