services:
  swagger-editor:
    image: swaggerapi/swagger-editor:v5.6.2-unprivileged
    networks:
      - service_access_link
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager

  swagger-ui:
    image: swaggerapi/swagger-ui:v5.32.6
    ports:
      - target: 8080
        published: 16080
        protocol: tcp
        mode: host
    volumes:
      - ${TSW_REMOTE_STACK_ROOT:-/var/lib/tiny-swarm-world/stacks}/swagger/swagger/openapi.json:/openapi.json:ro
    environment:
      SWAGGER_JSON: /openapi.json
      # API_URL: ""
    networks:
      - service_access_link
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager

  swagger-api:
    image: danielgtaylor/apisprout
    volumes:
      - ${TSW_REMOTE_STACK_ROOT:-/var/lib/tiny-swarm-world/stacks}/swagger/swagger/openapi.json:/openapi.json:ro
    command: /openapi.json
    networks:
      service_access_link:
        aliases:
          - local.swagger.apisprout
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager

  swagger-nginx:
    image: nginx:mainline-alpine
    ports:
      - target: 8084
        published: 16081
        protocol: tcp
        mode: host
    volumes:
      - ${TSW_REMOTE_STACK_ROOT:-/var/lib/tiny-swarm-world/stacks}/swagger/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      service_access_link:
        aliases:
          - local.swagger.api
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager
networks:
  service_access_link:
    name: service_access_link
    external: true
