commands:
  - index: 1
    description: "Getting current bridge list of multipass"
    command: "multipass exec {vm_instance} -- bash -c \"docker network ls --format '{{{{.Name}}}} {{{{.Driver}}}}' | awk '\\$2 == \\\"bridge\\\" {{ print \\$1 }}'\""
    runner: "async"
    command_type: "hostos"
    vm_type:
      - "manager"
