from __future__ import annotations

import argparse
import base64
import hashlib
import hmac
import json
import os
import secrets
import shlex
import shutil
import subprocess
import sys
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Mapping, Sequence


RESET_CONFIRMATION = "RESET_TINY_SWARM_PLATFORM"
DEFAULT_SERVICE_PROFILE = "service-access"
DEFAULT_SECRET_ENV_FILE = ".tiny-swarm-world/local/live-installation.env"
DEFAULT_INFISICAL_SECRET_ENV_FILE = ".tiny-swarm/secrets/bootstrap.local.env"
DEFAULT_GENERATED_SECRET_ENV_FILE = ".tiny-swarm/secrets/generated.local.env"
DEFAULT_NATIVE_LINUX_VENV = ".tiny-swarm-world/install-venv"
DEFAULT_SECRET_MANIFEST_PATH = Path("infra/config/secrets/infisical-secrets.yaml")
INSTALLER_REQUIRED_SOURCES = {"generated_local_secret", "placeholder_only"}


@dataclass(frozen=True)
class InstallerOptions:
    service_profile: str
    generate_secrets: bool
    confirm_reset: bool
    non_interactive_live_approval: bool
    headless: bool


@dataclass(frozen=True)
class InstallerPaths:
    secret_env_file: Path
    infisical_secret_env_file: Path
    generated_secret_env_file: Path
    native_linux_venv: Path


@dataclass(frozen=True)
class HostRuntime:
    name: str
    detection_source: str


@dataclass(frozen=True)
class InstallerSecretEntry:
    key: str
    source: str
    required: bool


class InstallerError(RuntimeError):
    pass


def main(argv: Sequence[str] | None = None) -> int:
    try:
        return run(parse_args(argv), env=os.environ, cwd=Path.cwd())
    except InstallerError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1


def parse_args(argv: Sequence[str] | None = None) -> InstallerOptions:
    parser = argparse.ArgumentParser(description="Tiny Swarm World live installation wrapper.")
    parser.add_argument(
        "--service-profile",
        default=os.environ.get("SERVICE_PROFILE", DEFAULT_SERVICE_PROFILE),
        choices=("default", "service-access"),
        help="Service profile passed to setup run.",
    )
    parser.add_argument(
        "--no-generate-secrets",
        action="store_true",
        help="Fail if required TSW_* secrets are missing.",
    )
    parser.add_argument(
        "--confirm-reset",
        action="store_true",
        help="Confirm the governed fresh-install reset without prompting.",
    )
    parser.add_argument(
        "--non-interactive-live-approval",
        action="store_true",
        help="Pass explicit non-interactive live approval to the CLI.",
    )
    parser.add_argument(
        "--headless",
        action="store_true",
        help="Disable terminal recorder/TUI presentation and capture command output directly.",
    )
    args = parser.parse_args(argv)
    return InstallerOptions(
        service_profile=args.service_profile,
        generate_secrets=not args.no_generate_secrets,
        confirm_reset=args.confirm_reset,
        non_interactive_live_approval=args.non_interactive_live_approval,
        headless=args.headless or os.environ.get("TSW_INSTALL_HEADLESS") == "1",
    )


def run(
    options: InstallerOptions,
    *,
    env: Mapping[str, str],
    cwd: Path,
) -> int:
    _require_repository(cwd)
    paths = _paths_from_env(env, cwd)
    host_runtime = detect_host_runtime(env)
    python_bin = ensure_python_environment(host_runtime, paths, env)
    install_env = dict(env)

    _ensure_private_file(paths.secret_env_file)
    _ensure_private_file(paths.infisical_secret_env_file)
    _ensure_private_file(paths.generated_secret_env_file)
    install_env.update(_load_export_file(paths.secret_env_file))
    install_env.update(_load_export_file(paths.infisical_secret_env_file))

    required_entries = _required_installer_secret_entries(cwd / DEFAULT_SECRET_MANIFEST_PATH)
    missing = [entry for entry in required_entries if not install_env.get(entry.key)]
    secrets_generated_count = 0
    if missing:
        if not options.generate_secrets:
            _print_missing_secrets([entry.key for entry in missing])
            raise InstallerError(
                f"Provide the missing values in {paths.secret_env_file.as_posix()} "
                "or remove --no-generate-secrets."
            )
        generated = _generated_secret_values(missing, install_env)
        _append_exports(
            paths.secret_env_file,
            f"Generated by install.sh at {_utc_timestamp()} UTC",
            generated,
        )
        install_env.update(generated)
        secrets_generated_count = len(missing)

    _ensure_sonarqube_password_policy(options, paths, install_env)
    _ensure_default_config_exports(paths, install_env)
    _write_infisical_secret_file(paths.infisical_secret_env_file, install_env)
    install_env.setdefault("TSW_SEED_INFISICAL_ITEMS", "0")
    _configure_native_linux_command_group(host_runtime, install_env)

    if _inside_git_worktree(cwd) and not _git_check_ignore(cwd, ".tiny-swarm-world/"):
        print(
            "WARN: .tiny-swarm-world/ is not ignored by git; do not commit local evidence or generated secrets.",
            file=sys.stderr,
        )

    run_id = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    evidence_dir = cwd / ".tiny-swarm-world" / "evidence" / "installation-tests" / host_runtime.name / run_id
    evidence_dir.mkdir(parents=True, exist_ok=True)
    live_mode, approval_source, approval_argument = _live_approval(options)
    terminal_mode = "headless" if options.headless else "terminal_recorder"
    _write_context(
        evidence_dir,
        run_id=run_id,
        service_profile=options.service_profile,
        secret_env_file=paths.secret_env_file,
        secrets_generated_count=secrets_generated_count,
        host_runtime=host_runtime,
        live_execution_mode=live_mode,
        live_approval_source=approval_source,
        terminal_recording_mode=terminal_mode,
        cwd=cwd,
        env=install_env,
    )

    _print_install_plan(cwd, options, evidence_dir, paths.secret_env_file)
    _confirm_reset(options)
    if not options.headless and shutil.which("script") is None:
        raise InstallerError("Required command 'script' is not available for terminal recording. Use --headless to capture logs directly.")
    _append_context(
        evidence_dir,
        {
            "reset_confirmation_present": "yes",
            "reset_confirmation_source": "explicit_flag" if options.confirm_reset else "interactive_prompt",
        },
    )

    reset_command = _workflow_command(
        python_bin,
        "platform reset",
        f"--live{approval_argument} --confirm {RESET_CONFIRMATION} --service-profile {shlex.quote(options.service_profile)}",
    )
    setup_command = _workflow_command(
        python_bin,
        "setup run",
        f"--live{approval_argument} --service-profile {shlex.quote(options.service_profile)}",
    )

    reset_exit = _run_phase(
        "fresh-install reset",
        reset_command,
        evidence_dir / "reset-run.log",
        options,
        install_env,
        cwd,
    )
    _write_text(evidence_dir / "reset-run.exit", f"{reset_exit}\n")
    _append_context(evidence_dir, {"reset_exit": str(reset_exit)})
    if reset_exit != 0:
        print(f"Fresh-install reset failed with exit code {reset_exit}. Setup will not start.", file=sys.stderr)
        print(f"Evidence directory: {evidence_dir.as_posix()}", file=sys.stderr)
        _append_context(
            evidence_dir,
            {
                "setup_skipped_due_to_reset_failure": "yes",
                "finished_utc": _utc_timestamp(),
            },
        )
        _print_tail(evidence_dir / "reset-run.log", "Last reset log lines")
        return reset_exit

    setup_exit = _run_phase(
        "live setup",
        setup_command,
        evidence_dir / "setup-run.log",
        options,
        install_env,
        cwd,
    )
    _write_text(evidence_dir / "setup-run.exit", f"{setup_exit}\n")
    _append_context(
        evidence_dir,
        {
            "setup_exit": str(setup_exit),
            "finished_utc": _utc_timestamp(),
        },
    )
    if setup_exit == 0:
        print("Installation completed successfully.")
        print(f"Evidence directory: {evidence_dir.as_posix()}")
    else:
        print(f"Installation failed with exit code {setup_exit}.", file=sys.stderr)
        print(f"Evidence directory: {evidence_dir.as_posix()}", file=sys.stderr)
        _print_tail(evidence_dir / "setup-run.log", "Last log lines")
    return setup_exit


def _paths_from_env(env: Mapping[str, str], cwd: Path) -> InstallerPaths:
    def resolve(path_value: str) -> Path:
        path = Path(path_value)
        return path if path.is_absolute() else cwd / path

    return InstallerPaths(
        secret_env_file=resolve(env.get("TSW_INSTALL_ENV_FILE", DEFAULT_SECRET_ENV_FILE)),
        infisical_secret_env_file=resolve(env.get("TSW_INFISICAL_SECRET_ENV_FILE", DEFAULT_INFISICAL_SECRET_ENV_FILE)),
        generated_secret_env_file=resolve(env.get("TSW_GENERATED_SECRET_ENV_FILE", DEFAULT_GENERATED_SECRET_ENV_FILE)),
        native_linux_venv=resolve(env.get("TSW_NATIVE_LINUX_VENV", DEFAULT_NATIVE_LINUX_VENV)),
    )


def _require_repository(cwd: Path) -> None:
    if not (cwd / "src" / "tiny_swarm_world").is_dir():
        raise InstallerError("Run this script from the Tiny Swarm World repository root.")


def _required_installer_secret_entries(manifest_path: Path) -> tuple[InstallerSecretEntry, ...]:
    try:
        import yaml

        payload = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as error:
        raise InstallerError(f"Secret manifest is invalid: {error}") from error
    if not isinstance(payload, dict) or not isinstance(payload.get("secrets"), list):
        raise InstallerError("Secret manifest is invalid: expected a secrets list.")
    entries = tuple(_installer_secret_entry(item) for item in payload["secrets"])
    return tuple(
        entry
        for entry in entries
        if entry.required and entry.source in INSTALLER_REQUIRED_SOURCES
    )


def _installer_secret_entry(item: object) -> InstallerSecretEntry:
    if not isinstance(item, dict):
        raise InstallerError("Secret manifest is invalid: secret entries must be mappings.")
    key = str(item.get("key", ""))
    source = str(item.get("source", ""))
    if not key.startswith("TSW_"):
        raise InstallerError(f"Secret manifest is invalid: unsupported key {key!r}.")
    return InstallerSecretEntry(
        key=key,
        source=source,
        required=bool(item.get("required", False)),
    )


def detect_host_runtime(env: Mapping[str, str]) -> HostRuntime:
    test_runtime = env.get("TSW_INSTALL_TEST_HOST_RUNTIME")
    if env.get("TSW_INSTALL_TEST_MODE") == "1" and test_runtime in {"wsl2", "native_linux"}:
        return HostRuntime(test_runtime, "test_override")
    if env.get("WSL_DISTRO_NAME") or env.get("WSL_INTEROP"):
        return HostRuntime("wsl2", "wsl_environment")
    kernel_text = _read_text(Path("/proc/sys/kernel/osrelease")).casefold()
    version_text = _read_text(Path("/proc/version")).casefold()
    if "microsoft" in kernel_text or "wsl" in kernel_text or "microsoft" in version_text or "wsl" in version_text:
        return HostRuntime("wsl2", "kernel_signal")
    return HostRuntime("native_linux", "uname_linux_without_wsl_signal")


def ensure_python_environment(
    host_runtime: HostRuntime,
    paths: InstallerPaths,
    env: Mapping[str, str],
) -> str:
    python_bin = "python3"
    if host_runtime.name == "wsl2" or env.get("TSW_INSTALL_SKIP_NATIVE_DEPENDENCY_BOOTSTRAP") == "1":
        return python_bin
    if _python_imports_available(python_bin, env):
        return python_bin
    venv_python = paths.native_linux_venv / "bin" / "python"
    if venv_python.is_file() and _python_imports_available(venv_python.as_posix(), env):
        return venv_python.as_posix()
    print(f"Native Linux Python dependencies are missing; preparing {paths.native_linux_venv.as_posix()}.", file=sys.stderr)
    if env.get("TSW_INSTALL_TEST_MODE") == "1" and env.get("TSW_INSTALL_TEST_FORCE_MISSING_IMPORTS") == "1":
        _write_test_venv_python(venv_python)
        if not _python_imports_available(venv_python.as_posix(), env):
            raise InstallerError("Native Linux Python dependency bootstrap did not make required modules importable.")
        return venv_python.as_posix()
    completed = subprocess.run(
        [python_bin, "-m", "venv", paths.native_linux_venv.as_posix()],
        env=dict(env),
        check=False,
    )
    if completed.returncode != 0:
        raise InstallerError(
            f"Could not create native Linux virtual environment at {paths.native_linux_venv.as_posix()}. "
            "Install python3-venv and rerun install.sh."
        )
    subprocess.run(
        [venv_python.as_posix(), "-m", "pip", "install", "--upgrade", "pip"],
        env=dict(env),
        check=True,
    )
    subprocess.run(
        [venv_python.as_posix(), "-m", "pip", "install", "-r", "requirements.txt"],
        env=dict(env),
        check=True,
    )
    if not _python_imports_available(venv_python.as_posix(), env):
        raise InstallerError("Native Linux Python dependency bootstrap did not make required modules importable.")
    return venv_python.as_posix()


def _write_test_venv_python(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "\n".join(
            (
                "#!/usr/bin/env bash",
                "set -euo pipefail",
                'if [[ "${1:-}" == "-c" ]]; then exit 0; fi',
                'if [[ "${1:-}" == "-m" && "${2:-}" == "pip" ]]; then exit 0; fi',
                "exit 44",
                "",
            )
        ),
        encoding="utf-8",
    )
    path.chmod(0o755)


def _python_imports_available(python_bin: str, env: Mapping[str, str]) -> bool:
    if (
        env.get("TSW_INSTALL_TEST_MODE") == "1"
        and env.get("TSW_INSTALL_TEST_FORCE_MISSING_IMPORTS") == "1"
        and python_bin == "python3"
    ):
        return False
    code = "import pydantic\nimport requests\nimport ruamel.yaml\nimport yaml\n"
    return subprocess.run(
        [python_bin, "-c", code],
        env=dict(env),
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    ).returncode == 0


def _load_export_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        assignment = _export_assignment_from_line(raw_line)
        if assignment is None:
            continue
        name, raw_value = assignment
        values[name] = _parse_export_value(raw_value)
    return values


def _export_assignment_from_line(raw_line: str) -> tuple[str, str] | None:
    line = raw_line.strip()
    if not line or line.startswith("#"):
        return None
    if line.startswith("export "):
        line = line.removeprefix("export ").strip()
    if "=" not in line:
        return None
    name, raw_value = line.split("=", 1)
    if not name.isidentifier():
        return None
    return name, raw_value


def _parse_export_value(raw_value: str) -> str:
    try:
        parsed = shlex.split(raw_value, posix=True)
    except ValueError:
        parsed = [raw_value]
    return parsed[0] if parsed else ""


def _generated_secret_values(
    entries: Sequence[InstallerSecretEntry],
    current_env: Mapping[str, str] | None = None,
) -> dict[str, str]:
    current_values = dict(current_env or {})
    generated: dict[str, str] = {}
    for entry in entries:
        name = entry.key
        if name == "TSW_INFISICAL_ENCRYPTION_KEY":
            generated[name] = secrets.token_hex(16)
        elif name == "TSW_INFISICAL_LOGIN_EMAIL":
            generated[name] = "admin@tiny-swarm-world.local"
        elif name == "TSW_SONARQUBE_ADMIN_PASSWORD":
            generated[name] = f"{secrets.token_urlsafe(32)}!"
        elif name == "TSW_PULSAR_TOKEN_SECRET_KEY":
            generated[name] = _generated_pulsar_token_secret_key()
            generated["TSW_PULSAR_ADMIN_TOKEN"] = _generated_pulsar_admin_token(
                generated[name],
            )
        elif name == "TSW_PULSAR_ADMIN_TOKEN":
            secret_key = (
                generated.get("TSW_PULSAR_TOKEN_SECRET_KEY")
                or current_values.get("TSW_PULSAR_TOKEN_SECRET_KEY")
                or _generated_pulsar_token_secret_key()
            )
            generated.setdefault("TSW_PULSAR_TOKEN_SECRET_KEY", secret_key)
            generated[name] = _generated_pulsar_admin_token(secret_key)
        else:
            generated[name] = secrets.token_urlsafe(32)
    return generated


def _generated_pulsar_token_secret_key() -> str:
    return base64.b64encode(secrets.token_bytes(32)).decode("ascii")


def _generated_pulsar_admin_token(secret_key: str) -> str:
    key = base64.b64decode(secret_key)
    header = _base64url_json({"alg": "HS256", "typ": "JWT"})
    payload = _base64url_json({"sub": "admin"})
    signing_input = f"{header}.{payload}".encode("ascii")
    signature = hmac.new(key, signing_input, hashlib.sha256).digest()
    return f"{header}.{payload}.{_base64url(signature)}"


def _base64url_json(payload: Mapping[str, str]) -> str:
    return _base64url(json.dumps(payload, separators=(",", ":")).encode("utf-8"))


def _base64url(payload: bytes) -> str:
    return base64.urlsafe_b64encode(payload).decode("ascii").rstrip("=")


def _ensure_sonarqube_password_policy(
    options: InstallerOptions,
    paths: InstallerPaths,
    env: dict[str, str],
) -> None:
    current = env.get("TSW_SONARQUBE_ADMIN_PASSWORD", "")
    if len(current) >= 12 and any(character in current for character in "!@#$%^&*()_+"):
        return
    if not options.generate_secrets:
        raise InstallerError("TSW_SONARQUBE_ADMIN_PASSWORD must be at least 12 characters and contain a special character.")
    value = f"{secrets.token_urlsafe(32)}!"
    env["TSW_SONARQUBE_ADMIN_PASSWORD"] = value
    exports = {"TSW_SONARQUBE_ADMIN_PASSWORD": value}
    label = f"Regenerated by install.sh for SonarQube password policy at {_utc_timestamp()} UTC"
    _append_exports(paths.secret_env_file, label, exports)
    _append_exports(paths.generated_secret_env_file, label, exports)


def _ensure_default_config_exports(paths: InstallerPaths, env: dict[str, str]) -> None:
    exports: dict[str, str] = {}
    if not env.get("TSW_TRAEFIK_TLS_CERT_SECRET_NAME"):
        exports["TSW_TRAEFIK_TLS_CERT_SECRET_NAME"] = "tsw_traefik_tls_cert"
    if not env.get("TSW_TRAEFIK_TLS_KEY_SECRET_NAME"):
        exports["TSW_TRAEFIK_TLS_KEY_SECRET_NAME"] = "tsw_traefik_tls_key"
    if not exports:
        return
    env.update(exports)
    _append_exports(
        paths.secret_env_file,
        f"Default non-secret config values written by install.sh at {_utc_timestamp()} UTC",
        exports,
    )


def _write_infisical_secret_file(path: Path, env: Mapping[str, str]) -> None:
    exports = {
        "TSW_INFISICAL_ENCRYPTION_KEY": env["TSW_INFISICAL_ENCRYPTION_KEY"],
        "TSW_INFISICAL_AUTH_SECRET": env["TSW_INFISICAL_AUTH_SECRET"],
        "TSW_INFISICAL_POSTGRES_PASSWORD": env["TSW_INFISICAL_POSTGRES_PASSWORD"],
        "TSW_INFISICAL_REDIS_PASSWORD": env["TSW_INFISICAL_REDIS_PASSWORD"],
        "TSW_INFISICAL_LOGIN_EMAIL": env["TSW_INFISICAL_LOGIN_EMAIL"],
        "TSW_INFISICAL_BOOTSTRAP_ADMIN_PASSWORD": env["TSW_INFISICAL_BOOTSTRAP_ADMIN_PASSWORD"],
        "ENCRYPTION_KEY": env["TSW_INFISICAL_ENCRYPTION_KEY"],
        "AUTH_SECRET": env["TSW_INFISICAL_AUTH_SECRET"],
        "POSTGRES_PASSWORD": env["TSW_INFISICAL_POSTGRES_PASSWORD"],
        "REDIS_PASSWORD": env["TSW_INFISICAL_REDIS_PASSWORD"],
        "INITIAL_BOOTSTRAP_ADMIN_PASSWORD": env["TSW_INFISICAL_BOOTSTRAP_ADMIN_PASSWORD"],
    }
    _write_exports(path, "Generated by install.sh. Do not commit.", exports)


def _configure_native_linux_command_group(host_runtime: HostRuntime, env: dict[str, str]) -> None:
    if host_runtime.name == "wsl2" or env.get("TSW_INSTALL_SKIP_NATIVE_GROUP_SWITCH") == "1":
        return
    if not shutil.which("sg") or not shutil.which("lxc"):
        return
    current_groups = subprocess.run(["id", "-nG"], text=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, check=False)
    if "lxd" in current_groups.stdout.split():
        return
    user = subprocess.run(["id", "-un"], text=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, check=False).stdout.strip()
    group = subprocess.run(["getent", "group", "lxd"], text=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, check=False)
    if group.returncode == 0 and user and user in group.stdout.partition(":")[2].split(":")[-1].split(","):
        env["TSW_INSTALL_COMMAND_GROUP"] = "lxd"
        print("Native Linux LXD group membership exists but is not active; running live commands through sg lxd.", file=sys.stderr)


def _confirm_reset(options: InstallerOptions) -> None:
    if options.confirm_reset:
        print("Fresh-install reset confirmed by explicit --confirm-reset flag.")
        return
    print("Fresh install will reset configured Tiny Swarm World managed state.")
    try:
        answer = input(f"Type {RESET_CONFIRMATION} to continue: ")
    except EOFError:
        raise InstallerError("Fresh-install reset confirmation was not provided.") from None
    if answer != RESET_CONFIRMATION:
        raise InstallerError("Fresh-install reset confirmation did not match.")


def _live_approval(options: InstallerOptions) -> tuple[str, str, str]:
    if options.non_interactive_live_approval:
        return "non_interactive", "explicit_automation_flag", " --approve-live"
    return "interactive", "operator_prompt", ""


def _workflow_command(python_bin: str, workflow: str, args: str) -> str:
    return f"PYTHONPATH=src {shlex.quote(python_bin)} -m tiny_swarm_world {workflow} {args}"


def _run_phase(
    name: str,
    command: str,
    log_file: Path,
    options: InstallerOptions,
    env: Mapping[str, str],
    cwd: Path,
) -> int:
    if options.headless:
        print(f"Starting {name}. Headless output is recorded at: {log_file.as_posix()}")
    else:
        print(f"Starting {name}. Terminal UI is visible and recorded at: {log_file.as_posix()}")
    log_file.parent.mkdir(parents=True, exist_ok=True)
    effective_command = command
    if env.get("TSW_INSTALL_COMMAND_GROUP"):
        effective_command = f"sg {env['TSW_INSTALL_COMMAND_GROUP']} -c {shlex.quote(command)}"
    if options.headless:
        with log_file.open("w", encoding="utf-8") as output:
            completed = subprocess.run(
                ["bash", "-lc", effective_command],
                cwd=cwd,
                env=dict(env),
                stdout=output,
                stderr=subprocess.STDOUT,
                check=False,
            )
        return completed.returncode
    return subprocess.run(
        ["script", "-q", "-e", "-c", effective_command, log_file.as_posix()],
        cwd=cwd,
        env=dict(env),
        check=False,
    ).returncode


def _write_context(
    evidence_dir: Path,
    *,
    run_id: str,
    service_profile: str,
    secret_env_file: Path,
    secrets_generated_count: int,
    host_runtime: HostRuntime,
    live_execution_mode: str,
    live_approval_source: str,
    terminal_recording_mode: str,
    cwd: Path,
    env: Mapping[str, str],
) -> None:
    values = {
        "run_id": run_id,
        "started_utc": _utc_timestamp(),
        "repo": cwd.as_posix(),
        "git_branch": _run_text(("git", "branch", "--show-current"), cwd=cwd),
        "git_head": _run_text(("git", "rev-parse", "--short", "HEAD"), cwd=cwd),
        "service_profile": service_profile,
        "fresh_install_reset": "required",
        "secret_env_file": secret_env_file.as_posix(),
        "secrets_generated_count": str(secrets_generated_count),
        "host_runtime_type": host_runtime.name,
        "host_runtime_detection_source": host_runtime.detection_source,
        "selected_evidence_directory": evidence_dir.as_posix(),
        "live_execution_mode": live_execution_mode,
        "live_approval_source": live_approval_source,
        "terminal_recording_mode": terminal_recording_mode,
        "platform_system": _run_text(("uname", "-s")),
        "kernel_release": _run_text(("uname", "-r")),
        "proc_osrelease": _read_text(Path("/proc/sys/kernel/osrelease")).strip(),
        "wsl_distro_name_present": "yes" if env.get("WSL_DISTRO_NAME") else "no",
        "wsl_interop_present": "yes" if env.get("WSL_INTEROP") else "no",
    }
    _append_context(evidence_dir, values, replace=True)


def _append_context(evidence_dir: Path, values: Mapping[str, str], *, replace: bool = False) -> None:
    mode = "w" if replace else "a"
    with (evidence_dir / "context.txt").open(mode, encoding="utf-8") as context:
        for key, value in values.items():
            context.write(f"{key}={value}\n")


def _print_install_plan(cwd: Path, options: InstallerOptions, evidence_dir: Path, secret_env_file: Path) -> None:
    print(
        "\n".join(
            (
                "Tiny Swarm World live installation",
                "",
                f"Repository:      {cwd.as_posix()}",
                f"Service profile: {options.service_profile}",
                f"Evidence:        {evidence_dir.as_posix()}",
                f"Secret file:     {secret_env_file.as_posix()}",
                "",
                "This will run live infrastructure automation. It may create or change VMs,",
                "Docker resources, local service state, networks, and deployment artifacts.",
                "Fresh install starts by resetting configured Tiny Swarm World managed state.",
            )
        )
    )


def _print_missing_secrets(missing: Sequence[str]) -> None:
    print("Missing required secrets:", file=sys.stderr)
    for name in missing:
        print(f"  {name}", file=sys.stderr)


def _print_tail(path: Path, title: str) -> None:
    print(f"\n{title}:", file=sys.stderr)
    if not path.exists():
        return
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()[-80:]
    for line in lines:
        print(line, file=sys.stderr)


def _append_exports(path: Path, label: str, values: Mapping[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as file:
        file.write(f"\n# {label}\n")
        for key, value in values.items():
            file.write(f"export {key}={shlex.quote(value)}\n")
    path.chmod(0o600)


def _write_exports(path: Path, label: str, values: Mapping[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as file:
        file.write(f"# {label}\n")
        for key, value in values.items():
            file.write(f"export {key}={shlex.quote(value)}\n")
    path.chmod(0o600)


def _ensure_private_file(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.touch(exist_ok=True)
    path.chmod(0o600)


def _write_text(path: Path, value: str) -> None:
    path.write_text(value, encoding="utf-8")


def _read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _run_text(command: tuple[str, ...], *, cwd: Path | None = None) -> str:
    return subprocess.run(
        command,
        cwd=cwd,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        check=False,
    ).stdout.strip()


def _inside_git_worktree(cwd: Path) -> bool:
    return subprocess.run(["git", "rev-parse", "--is-inside-work-tree"], cwd=cwd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False).returncode == 0


def _git_check_ignore(cwd: Path, path: str) -> bool:
    return subprocess.run(["git", "check-ignore", "-q", path], cwd=cwd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False).returncode == 0


def _utc_timestamp() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


if __name__ == "__main__":
    raise SystemExit(main())
