"""Compatibility entry point for the installation application service."""

from __future__ import annotations
from collections.abc import Mapping, Sequence
from pathlib import Path
from tiny_swarm_world.infrastructure.composition_installation import (
    build_installation_service,
)
from tiny_swarm_world.infrastructure.composition_installation import (
    main as _main,
)
from tiny_swarm_world.application.ports.installation import (
    InstallerOptions,
    InstallerPaths,
    _GitProbeResult,
    _EvidenceProbeSnapshot,
    _InstallRunContext,
    HostRuntime,
    InstallerSecretEntry,
    WindowsWslBridgeGuardResult,
    InstallReporter,
    _FallbackInstallEvent,
    InstallerError,
    RESET_CONFIRMATION,
    _RESET_RUN_LOG_FILE,
    _SETUP_RUN_LOG_FILE,
    DEFAULT_SERVICE_PROFILE,
    DEFAULT_SECRET_ENV_FILE,
    DEFAULT_NATIVE_LINUX_VENV,
    DEFAULT_SECRET_MANIFEST_PATH,
    TRAEFIK_GUI_USERS_HTPASSWD_ENVIRONMENT,
    INSTALLER_SUBPROCESS_TIMEOUT_ENVIRONMENT,
    DEFAULT_INSTALLER_SUBPROCESS_TIMEOUT_SECONDS,
    DEFAULT_INSTALLER_PROBE_TIMEOUT_SECONDS,
    WINDOWS_WSL_BRIDGE_MAX_AGE_SECONDS,
    WINDOWS_EXPOSURE_ENVIRONMENT,
    WINDOWS_WSL_BRIDGE_TEST_STATE_ENVIRONMENT,
)
from tiny_swarm_world.infrastructure.composition_installation import (
    _configuration_snapshot,
    _copy_configuration_directory,
    _copy_configuration_file,
    _copy_configuration_tree,
    _open_configuration_source,
    _paths_from_env,
    _validate_native_installation_read_only,
    _validate_snapshot_storage,
)
from tiny_swarm_world.infrastructure.composition_installation import (
    _ensure_default_config_exports,
    _normalize_infisical_login_email,
    _normalized_email_value,
    _require_operator_provisioned_traefik_gui_users,
    _required_installer_secret_entries,
    _resolve_internal_test_installer_values,
)
from tiny_swarm_world.infrastructure.composition_installation import (
    _append_context,
    _collect_evidence_probe_snapshot,
    _git_revision_metadata,
    _installation_evidence_directory,
    _probe_git_ignore,
    _read_text,
    _safe_credential_source_metadata,
    _utc_timestamp,
    _windows_wsl_bridge_context,
    _write_context,
    _write_text,
)
from tiny_swarm_world.infrastructure.composition_installation import (
    _require_repository,
    _windows_exposure_required,
    _windows_wsl_bridge_expected_ports,
    _windows_wsl_bridge_guard,
    authorize_project_filesystem,
    detect_host_runtime,
)
from tiny_swarm_world.infrastructure.composition_installation import (
    _FallbackInstallReporter,
    _confirm_reset,
    _default_install_reporter,
    _format_ints,
    _has_setup_network_failure,
    _live_approval,
    _phase_event,
    _print_install_completion_summary,
    _print_install_plan,
    _print_reset_failure_guidance,
    _print_setup_failure_guidance,
    _print_tail,
    _print_windows_wsl_bridge_failure,
    _relative_display_path,
    _render_fallback_install_event,
    _reset_failure_guidance_lines,
    _reset_log_mentions,
    _safe_installer_line_value,
    _safe_log_tail_lines,
    _setup_failure_guidance_lines,
    _starts_structured_log_value,
    _structured_delimiter_delta,
    _suggested_checks_for_phase,
    _windows_wsl_bridge_suggested_commands,
    parse_args,
)
from tiny_swarm_world.infrastructure.composition_installation import (
    _filesystem_override_argument,
    _installer_subprocess_timeout_seconds,
    _python_imports_available,
    _run_installer_subprocess,
    _run_optional_text,
    _run_phase,
    _run_text,
    _workflow_command,
    _write_test_venv_python,
    ensure_python_environment,
)
from tiny_swarm_world.domain.project_filesystem import ProjectFilesystemKind
from tiny_swarm_world.application.services.credential_resolution import (
    CREDENTIAL_SOURCE_MAP_ENVIRONMENT,
)
from tiny_swarm_world.infrastructure.composition_installation import (
    ProjectFilesystemInspector,
)

__all__ = [
    "InstallerOptions",
    "InstallerPaths",
    "_GitProbeResult",
    "_EvidenceProbeSnapshot",
    "_InstallRunContext",
    "HostRuntime",
    "InstallerSecretEntry",
    "WindowsWslBridgeGuardResult",
    "InstallReporter",
    "_FallbackInstallEvent",
    "InstallerError",
    "RESET_CONFIRMATION",
    "_RESET_RUN_LOG_FILE",
    "_SETUP_RUN_LOG_FILE",
    "DEFAULT_SERVICE_PROFILE",
    "DEFAULT_SECRET_ENV_FILE",
    "DEFAULT_NATIVE_LINUX_VENV",
    "DEFAULT_SECRET_MANIFEST_PATH",
    "TRAEFIK_GUI_USERS_HTPASSWD_ENVIRONMENT",
    "INSTALLER_SUBPROCESS_TIMEOUT_ENVIRONMENT",
    "DEFAULT_INSTALLER_SUBPROCESS_TIMEOUT_SECONDS",
    "DEFAULT_INSTALLER_PROBE_TIMEOUT_SECONDS",
    "WINDOWS_WSL_BRIDGE_MAX_AGE_SECONDS",
    "WINDOWS_EXPOSURE_ENVIRONMENT",
    "WINDOWS_WSL_BRIDGE_TEST_STATE_ENVIRONMENT",
    "_configuration_snapshot",
    "_copy_configuration_tree",
    "_validate_native_installation_read_only",
    "_copy_configuration_file",
    "_paths_from_env",
    "_open_configuration_source",
    "_copy_configuration_directory",
    "_validate_snapshot_storage",
    "_resolve_internal_test_installer_values",
    "_required_installer_secret_entries",
    "_ensure_default_config_exports",
    "_require_operator_provisioned_traefik_gui_users",
    "_normalize_infisical_login_email",
    "_normalized_email_value",
    "_windows_wsl_bridge_guard",
    "detect_host_runtime",
    "authorize_project_filesystem",
    "_windows_exposure_required",
    "_windows_wsl_bridge_expected_ports",
    "_require_repository",
    "_write_test_venv_python",
    "_filesystem_override_argument",
    "ensure_python_environment",
    "_run_installer_subprocess",
    "_run_text",
    "_installer_subprocess_timeout_seconds",
    "_run_phase",
    "_workflow_command",
    "_run_optional_text",
    "_python_imports_available",
    "_write_context",
    "_collect_evidence_probe_snapshot",
    "_installation_evidence_directory",
    "_utc_timestamp",
    "_safe_credential_source_metadata",
    "_git_revision_metadata",
    "_windows_wsl_bridge_context",
    "_write_text",
    "_read_text",
    "_probe_git_ignore",
    "_append_context",
    "_starts_structured_log_value",
    "_FallbackInstallReporter",
    "_print_setup_failure_guidance",
    "parse_args",
    "_live_approval",
    "_safe_installer_line_value",
    "_print_install_plan",
    "_format_ints",
    "_setup_failure_guidance_lines",
    "_print_tail",
    "_suggested_checks_for_phase",
    "_render_fallback_install_event",
    "_print_windows_wsl_bridge_failure",
    "_phase_event",
    "_reset_log_mentions",
    "_relative_display_path",
    "_confirm_reset",
    "_structured_delimiter_delta",
    "_has_setup_network_failure",
    "_print_reset_failure_guidance",
    "_safe_log_tail_lines",
    "_windows_wsl_bridge_suggested_commands",
    "_default_install_reporter",
    "_reset_failure_guidance_lines",
    "_print_install_completion_summary",
    "ProjectFilesystemKind",
    "CREDENTIAL_SOURCE_MAP_ENVIRONMENT",
    "ProjectFilesystemInspector",
    "main",
    "run",
]


def main(argv: Sequence[str] | None = None) -> int:
    return _main(argv)


def run(
    options: InstallerOptions,
    *,
    env: Mapping[str, str],
    cwd: Path,
    reporter: InstallReporter | None = None,
) -> int:
    return build_installation_service().run(
        options, env=env, cwd=cwd, reporter=reporter
    )


if __name__ == "__main__":
    raise SystemExit(main())
