network:
  version: 2
  renderer: networkd
  ethernets:
    ens3:
      dhcp4: no
      addresses:
        - 192.0.2.10/24
      routes:
        - to: 0.0.0.0/0
          via: 192.0.2.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
