services:
  jenkins:
    image: ${TSW_JENKINS_IMAGE:-127.0.0.1:13500/jenkins:latest}
    user: root
    environment:
      TSW_JENKINS_ADMIN_PASSWORD: ${TSW_JENKINS_ADMIN_PASSWORD}
    volumes:
      - jenkins_home:/var/lib/jenkins
    networks:
      - tiny_swarm_world_ingress
    ports:
      - target: 8080
        published: 11080
        protocol: tcp
        mode: host
      - target: 50000
        published: 11050
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
volumes:
  jenkins_home:

networks:
  tiny_swarm_world_ingress:
    name: tiny_swarm_world_ingress
    external: true
