services:
  jenkins:
    image: ${TSW_JENKINS_IMAGE:-127.0.0.1:13500/jenkins:latest}
    user: root
    environment:
      TSW_JENKINS_ADMIN_PASSWORD: ${TSW_JENKINS_ADMIN_PASSWORD}
    volumes:
      - jenkins_home:/var/lib/jenkins
    networks:
      - traefik_ingress
    ports:
      - target: 8080
        published: 11080
        protocol: tcp
        mode: host
      - target: 50000
        published: 11050
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik_ingress
        - traefik.http.routers.jenkins.rule=Host(`jenkins.tsw.local`)
        - traefik.http.routers.jenkins.entrypoints=websecure
        - traefik.http.routers.jenkins.tls=true
        - traefik.http.services.jenkins.loadbalancer.server.port=8080
      placement:
        constraints:
          - node.role == manager
volumes:
  jenkins_home:

networks:
  traefik_ingress:
    name: traefik_ingress
    external: true
