commands:
  - index: 1
    description: "Getting current ips of each vm"
    command: "multipass exec  {vm_instance} -- bash -c \"docker network inspect {docker_bridge} | jq -r ''.[0].Containers.\"ingress-sbox\".IPv4Address'\""
    runner: "async"
    command_type: "hostos"
    vm_type:
      - "manager"
      - "worker"
